version: '3.1'
services:
  stat-api:
    build:
      context: ./stats/statApi
      dockerfile: Dockerfile
    container_name: stat-api
    ports:
      - "9090:9090"
    depends_on:
      - stat-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stat-db:5432/ExploreWithMeDB
      - SPRING_DATASOURCE_USERNAME=ewm-user
      - SPRING_DATASOURCE_PASSWORD=123

  gateway:
    build:
      context: ./stats/gateway
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - stat-api
    environment:
      - STAT_API_URL=http://stat-api:9090

  stat-db:
    image: postgres:14-alpine
    container_name: stat-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_USER=ewm-user
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=ExploreWithMeDB