version: '3.1'
services:
  stats-server:
    build:
      context: ./stats-service/server
      dockerfile: Dockerfile
    container_name: stats-server
    ports:
      - "9088:9088"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ExploreWithMeDB
      - SPRING_DATASOURCE_USERNAME=ewm-user
      - SPRING_DATASOURCE_PASSWORD=123

  stats-client:
    build:
      context: ./stats-service/client
      dockerfile: Dockerfile
    container_name: stats-client
    ports:
      - "9090:9090"
    depends_on:
      - stats-server
    environment:
      - SERVER_URL=http://stats-server:9088

  ewm-service:
    build:
      context: ./ewm-service
      dockerfile: Dockerfile
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - ewm-db
      - stats-db
    environment:
      - STAT_API_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ExploreWithMeDBMain
      - SPRING_DATASOURCE_USERNAME=ewm-main-user
      - SPRING_DATASOURCE_PASSWORD=123

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_USER=ewm-user
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=ExploreWithMeDB

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_USER=ewm-main-user
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=ExploreWithMeDBMain
