version: '3.1'
services:
  common:
    build:
      context: ./mainService/common
      dockerfile: Dockerfile
    container_name: common
    depends_on:
      - main-db

  main-client:
    build:
      context: ./mainService/main-client
      dockerfile: Dockerfile
    container_name: main-client
    ports:
      - "8080:8080"
    depends_on:
      - service-public
    environment:
      - STAT_API_URL=http://service-admin:9091
      - STAT_API_URL=http://service-private:9092
      - STAT_API_URL=http://service-public:9093

  service-admin:
    build:
      context: ./mainService/admin
      dockerfile: Dockerfile
    container_name: service-admin
    ports:
      - "9091:9091"
    depends_on:
      - common
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/ExploreWithMeDBMain
      - SPRING_DATASOURCE_USERNAME=ewm-main-user
      - SPRING_DATASOURCE_PASSWORD=123

  service-private:
    build:
      context: ./mainService/private
      dockerfile: Dockerfile
    container_name: service-private
    ports:
      - "9092:9092"
    depends_on:
      - service-admin
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/ExploreWithMeDBMain
      - SPRING_DATASOURCE_USERNAME=ewm-main-user
      - SPRING_DATASOURCE_PASSWORD=123

  service-public:
    build:
      context: ./mainService/public
      dockerfile: Dockerfile
    container_name: service-public
    ports:
      - "9093:9093"
    depends_on:
      - service-private
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/ExploreWithMeDBMain
      - SPRING_DATASOURCE_USERNAME=ewm-main-user
      - SPRING_DATASOURCE_PASSWORD=123

  stats-server:
    build:
      context: ./stats/stats-server
      dockerfile: Dockerfile
    container_name: stats-server
    ports:
      - "9088:9088"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ExploreWithMeDB
      - SPRING_DATASOURCE_USERNAME=ewm-user
      - SPRING_DATASOURCE_PASSWORD=123

  ewm-service:
    build:
      context: ./stats/ewm-service
      dockerfile: Dockerfile
    container_name: ewm-service
    ports:
      - "9090:9090"
    depends_on:
      - stats-server
    environment:
      - STAT_API_URL=http://stats-server:9088

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_USER=ewm-user
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=ExploreWithMeDB

  main-db:
    image: postgres:14-alpine
    container_name: main-db
    ports:
      - "6543:5434"
    environment:
      - POSTGRES_USER=ewm-main-user
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=ExploreWithMeDBMain