spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

logging:
 level:
  org.springframework.web.client.RestTemplate: DEBUG

server:
  port: 9091

stats-server:
  url: http://host.docker.internal:9088