spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


logging:
 level:
  org.springframework.web.client.RestTemplate: DEBUG

server:
  port: 8080

statApi:
  url: http://host.docker.internal:9090