DROP TABLE IF EXISTS event_compilations;
DROP TABLE IF EXISTS participations;
DROP TABLE IF EXISTS event_categories;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS compilations;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category_name VARCHAR(50) NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id),
    CONSTRAINT uq_category_name UNIQUE (category_name)
    );

CREATE TABLE IF NOT EXISTS compilations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR(50) NOT NULL,
    pinned BOOLEAN NOT NULL,
    CONSTRAINT pk_compilations PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR(120) NOT NULL,
    annotation VARCHAR(2000) NOT NULL,
    category_id INTEGER NOT NULL,
    description VARCHAR(7000) NOT NULL,
    event_date TIMESTAMP NOT NULL,
    location_lat FLOAT NOT NULL,
    location_lon FLOAT NOT NULL,
    published_on TIMESTAMP,
    initiator_id INTEGER NOT NULL,
    paid BOOLEAN NOT NULL,
    participant_limit INTEGER NOT NULL,
    request_moderation BOOLEAN NOT NULL,
    event_state VARCHAR(50) NOT NULL,
    created_on TIMESTAMP NOT NULL,
    confirmed_requests INTEGER,
    views INTEGER NOT NULL,
    CONSTRAINT pk_events PRIMARY KEY (id),
    CONSTRAINT fk_category_event FOREIGN KEY (category_id) REFERENCES categories(id),
    CONSTRAINT fk_initiator_user FOREIGN KEY (initiator_id) REFERENCES users(id)
    );

CREATE TABLE IF NOT EXISTS participations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created TIMESTAMP NOT NULL,
    event_id INTEGER NOT NULL,
    requester_id INTEGER NOT NULL,
    status VARCHAR(255) NOT NULL,
    CONSTRAINT pk_participations PRIMARY KEY (id),
    CONSTRAINT uq_event_request UNIQUE (event_id, requester_id),
    CONSTRAINT fk_event_participation FOREIGN KEY (event_id) REFERENCES events(id),
    CONSTRAINT fk_requester_participation FOREIGN KEY (requester_id) REFERENCES users(id)
    );

CREATE TABLE IF NOT EXISTS event_categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id INTEGER NOT NULL,
    category_id INTEGER NOT NULL,
    CONSTRAINT pk_event_categories PRIMARY KEY (id),
    CONSTRAINT fk_category FOREIGN KEY (category_id) REFERENCES categories(id),
    CONSTRAINT fk_events FOREIGN KEY (event_id) REFERENCES events(id)
    );

CREATE TABLE IF NOT EXISTS event_compilations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id INTEGER NOT NULL,
    compilation_id INTEGER NOT NULL,
     CONSTRAINT pk_event_compilations PRIMARY KEY (id),
    CONSTRAINT fk_compilation FOREIGN KEY (compilation_id) REFERENCES compilations(id),
    CONSTRAINT fk_events_compilations FOREIGN KEY (event_id) REFERENCES events(id)
    );
