name: CI

on:
  push:
    branches:
      - main_svc

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: actions/setup-docker@v2
        with:
          dockerfile: ./mainService/main-client/Dockerfile

      - name: Build and run Docker container
        run: |
          docker-compose up -d
          docker ps -a
        timeout-minutes: 5
